[build]
  command = "npm run build"
  publish = "build"
  functions = "api"
  
# [[redirects]]
#   from = "/search"
#   to = "https://enq07qn14tpl.x.pipedream.net"
#   status = 200
#   force = true
#   signed = "API_SIGNATURE_TOKEN"
#   headers = {Authorization = "Netlify"}    
  
[[redirects]]
  from = "/search2"
  to = "https://enq07qn14tpl.x.pipedream.net"
  status = 200
  force = true

[[redirects]]
  from = "/search"
  status = 200
  force = true
  conditions = {Role = ["*"]}

[[redirects]]
  from = "/search/*"
  to = "/login.html"
  status = 401
  force = true

[[redirects]]
  from ="/*"
  to="/index.html"
  status=200