[build]
  command = "npm run build"
  publish = "build"
  functions = "api"

[[redirects]]
  from = "/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 401
  force = true
